/*
 * crc32c — the checksum every bitterfs block carries.
 *
 * Four steps, each erasing the one before it, which is why the function below
 * shows no sign of any of them.  Full derivation and measurements are in
 * docs/notes.tex.
 *
 *   1. A CRC is a REMAINDER: divide the message by a fixed polynomial in
 *      GF(2), where subtraction is XOR.  Hence long division written entirely
 *      with ^ and no arithmetic operators.
 *   2. One byte costs eight steps: test the low bit, shift right, XOR the
 *      polynomial if that bit was set.
 *   3. REFLECTION.  Catalogues name the polynomial 0x1EDC6F41; the table is
 *      built from its bit-reverse, 0x82F63B78.  Shifting left with the
 *      unreflected form is a correct CRC of something, but not crc32c —
 *      "123456789" gives 0x05440F15 rather than 0xE3069283, silently.
 *   4. A TABLE replaces the eight steps.  After `crc ^= byte` the high 24 bits
 *      are passengers; only the low 8 can reach bit 0 within eight shifts, so
 *      the polynomial's whole contribution depends on one byte.  256 possible
 *      contributions — that is crc32c_table.
 *
 * NOT the CRC-32 of zip, gzip and PNG.  cksum and zlib disagree with a
 * correct implementation of this file.
 */
#include "bitter_crc32c.h"
/* Generated by tools/gen_crc32c_table.c; regenerate with `make -C core table`.
 * A .h rather than a .c so `static` still hides it inside this translation
 * unit.  crc32c_table[0x80] == 0x82F63B78 is the check that it encodes the
 * right polynomial. */
#include "crc32c_table.h"

/*
 * The Sarwate algorithm: one lookup per byte in place of eight single-bit
 * steps.  `crc >> 8` is the passengers sliding down; the lookup is everything
 * those steps would have contributed.  Matches CRC_LE_BITS == 8 in the
 * kernel's lib/crc32.c.
 *
 * No initial value and no final XOR — callers own both, per the header.
 * Iterative rather than recursive by necessity: a per-byte recursion over a
 * 4096-byte block wants 4096 frames, and a kernel thread has 8–16 KB of stack.
 *
 * `const char *` is signed on x86-64, so bytes >= 0x80 sign-extend and flip
 * the top 24 bits of the XOR.  Verified harmless — exhaustively, against the
 * SSE4.2 crc32 instruction — because `& 0xFF` discards exactly those bits.
 * That is load-bearing on the mask, though: split this into the kernel's
 * two-statement form and it breaks.  `const bt_u8 *` would be safer.
 */
bt_u32 bt_crc32c(bt_u32 crc, const void* data, bt_u32 len) {
  const char* p = data;
  bt_u32 i = 0;
  while (i < len) {
    crc = crc32c_table[(crc ^ *p++) & 0xFF] ^ (crc >> 8);
    i++;
  }
  return crc; 
}

bt_u32 bt_block_csum(const void* buf, bt_u32 len) {
  return bt_crc32c(BT_CRC32C_INIT, (const bt_u8 *) buf + BITTER_CSUM_SIZE,
                   len - BITTER_CSUM_SIZE) ^ BT_CRC32C_INIT;
}
