/*
 * gen_crc32c_table.c — writes core/crc32c_table.h.  `make -C core table`.
 *
 * Run by hand, not by the build: the output is committed, because the
 * polynomial is fixed by the on-disk format and cannot change without
 * invalidating every existing image.
 *
 * In tools/ rather than core/ because it calls printf, so it is a hosted
 * program and could never compile into the kernel module — and core/ keeps
 * one invariant, that every file in it compiles freestanding.  Kept in the
 * repo rather than thrown away for the same reason the kernel keeps
 * lib/gen_crc32table.c: a 256-entry table with no generator beside it is 256
 * numbers nobody can reproduce.
 *
 * table[b] is the crc of the single byte b: eight rounds of "test the low bit,
 * shift right, XOR the polynomial if it was set", each round one step of long
 * division in GF(2).  Derivation is in core/bitter_crc32c.c and docs/notes.tex.
 */
#include <stdio.h>

/* The reflected form of 0x1EDC6F41, which is how catalogues and RFC 3720 name
 * this polynomial.  Written as the kernel writes it (CRC32C_POLY_LE): already
 * reversed, no flag.  Williams' generator uses the opposite convention —
 * TB_POLY = 0x04C11DB7 with TB_REVER = TRUE — and mixing the two gives a wrong
 * table with no diagnostic. */
#define POLY 0x82F63B78u

/* Matching ENTRIES_PER_LINE in the kernel's generator: short file, readable
 * diffs. */
#define ENTRIES_PER_LINE 4

/*
 * Everything to stdout; the Makefile owns the redirect and the atomic rename.
 * Deliberately not fopen()ing the output — a program that opened
 * crc32c_table.h itself would truncate the committed table before knowing it
 * could finish, and a half-written table is a silently wrong checksum.
 */
int main(void)
{
	unsigned i, k;

	/* The #include is load-bearing: `make -C core freestanding` compiles
	 * every header alone to prove it is self-contained, and a bare table
	 * mentioning bt_u32 would fail that. */
	printf("/* this file is generated by tools/gen_crc32c_table.c"
	       " - do not edit */\n");
	printf("/* regenerate with: make -C core table */\n\n");
	printf("#ifndef BITTER_CRC32C_TABLE_H\n");
	printf("#define BITTER_CRC32C_TABLE_H\n\n");
	printf("#include \"format/bitterfs_format.h\"\n\n");
	printf("/* crc32c (CRC-32/ISCSI), reflected polynomial 0x%08X.\n", POLY);
	printf(" * Checks: crc32c_table[0x00] == 0x00000000\n");
	printf(" *         crc32c_table[0x01] == 0xF26B8303\n");
	printf(" *         crc32c_table[0x80] == 0x%08X  (the polynomial itself)\n", POLY);
	printf(" *         XOR of all 256 entries == 0x00000000 */\n");
	printf("static const bt_u32 crc32c_table[256] = {\n");

	/* `crc` is declared inside the loop so it is necessarily reset per byte,
	 * and is 32-bit despite starting at 0..255 because the first XOR of POLY
	 * sets bits at position 31.  The trailing comma after the last element is
	 * legal C, which keeps this printf uniform. */
	for (i = 0; i < 256; i++) {
		unsigned crc = i;

		for (k = 0; k < 8; k++)
			crc = (crc & 1) ? (crc >> 1) ^ POLY : crc >> 1;

		printf("%s0x%08X,%s",
		       i % ENTRIES_PER_LINE == 0 ? "\t" : " ",
		       crc,
		       i % ENTRIES_PER_LINE == ENTRIES_PER_LINE - 1 ? "\n" : "");
	}

	printf("};\n\n");
	printf("#endif /* BITTER_CRC32C_TABLE_H */\n");

	return 0;
}
